app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/accounts/", include("accounts.api.urls", namespace="accounts-api")),
    path("api/categories/", include("categories.api.urls", namespace="categories-api")),
    path("api/calculate/", include("calculate.api.urls", namespace="calculate-api")),
    path("api/countries/", include("countries.api.urls", namespace="countries-api")),
    path(
        "api/destination/", include("destination.api.urls", namespace="destination-api")
    ),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("countries/", include("countries.urls", namespace="countries")),
    path("categories/", include("categories.urls", namespace="categories")),
]

countries/api/urls.py
from django.urls import path

from .views import CountryListAPIView

urlpatterns = [
    path("", CountryListAPIView.as_view(), name="index"),
]

app_name = "countries"

countries/urls.py
from django.urls import path

from .views import (
    CountryListView,
    CreateCountryView,
    DeleteCountryView,
    EditCountryView,
)

urlpatterns = [
    path("", CountryListView.as_view(), name="index"),
    path("create/", CreateCountryView.as_view(), name="create"),
    path("<int:pk>/edit/", EditCountryView.as_view(), name="edit"),
    path("<int:pk>/delete/", DeleteCountryView.as_view(), name="delete"),
]

app_name = "countries"

countries/models.py
from django.db import models


class Country(models.Model):
    name = models.CharField(max_length=25, unique=True)
    flag = models.URLField(max_length=255)
    currency = models.CharField(max_length=5, unique=True)

    class Meta:
        verbose_name = "Country"
        verbose_name_plural = "Countries"

    def __str__(self) -> str:
        return self.name

countries/forms.py
from django import forms

from .models import Country


class CreateCountryForm(forms.ModelForm):
    class Meta:
        model = Country
        fields = ["name", "flag", "currency"]


class EditCountryForm(forms.ModelForm):
    class Meta:
        model = Country
        fields = ["name", "flag", "currency"]

countries/api/views.py
from rest_framework import filters
from rest_framework.generics import ListAPIView

from countries.models import Country
from countries.serializer import CountrySerializer


class CountryListAPIView(ListAPIView):
    queryset = Country.objects.all().order_by("-id")
    serializer_class = CountrySerializer

    filter_backends = [filters.SearchFilter]
    search_fields = [
        "name",
    ]

countries/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from .forms import CreateCountryForm, EditCountryForm
from .models import Country


class CountryListView(ListView):
    model = Country
    queryset = Country.objects.all().order_by("-id")
    paginate_by = 10
    template_name = "countries/index.html"


class CreateCountryView(CreateView):
    model = Country
    form_class = CreateCountryForm
    template_name = "countries/create.html"
    success_url = reverse_lazy("countries:index")


class EditCountryView(UpdateView):
    model = Country
    form_class = EditCountryForm
    template_name = "countries/edit.html"
    success_url = reverse_lazy("countries:index")


class DeleteCountryView(DeleteView):
    model = Country
    template_name = "countries/delete.html"
    success_url = reverse_lazy("countries:index")

countries/templates/countries/add.html
{% extends "base.html" %} {% block title %} Add Country | BRCG 🚀 {% endblock %}
{% block content %}
<div class="d-flex align-items-center justify-content-center vh-100">
  <div class="row container-md justify-content-center">
    <div class="col-12 col-sm-5">
      <div class="card shadow">
        <div class="card-header text-center fw-bold">Add Country</div>

        <div class="card-body">
          <form action="{% url 'countries:add' %}" method="post">
            {% csrf_token %} {% for field in form %}
            <div class="mb-3">
              <label for="{{ field.label }}" class="form-label"
                >{{ field.label }}</label
              >

              <input
                id="{{ field.label }}"
                type="{{ field.field.widget.input_type }}"
                name="{{ field.name }}"
                class="form-control"
                value="{{ field.value|default:'' }}"
              />
              {% for error in field.errors %}
              <div class="form-text animate__animated animate__headShake">
                {{ error }}
              </div>
              {% endfor %}
            </div>
            {% endfor %}
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
              <a href="{% url 'countries:index' %}" class="btn btn-secondary">
                Back
              </a>
              <button type="submit" class="btn btn-primary">Add</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

countries/templates/countries/create.html
{% extends "base.html" %} {% block title %} Create Country | BRCG 🚀 {% endblock %} {% block content %}
<div class="d-flex align-items-center justify-content-center vh-100">
  <div class="row container-md justify-content-center">
    <div class="col-12 col-sm-5">
      <div class="card shadow">
        <div class="card-header text-center fw-bold">Create Country</div>

        <div class="card-body">
          <form action="{% url 'countries:create' %}" method="post">
            {% csrf_token %} {% for field in form %}
            <div class="mb-3">
              <label for="{{ field.label }}" class="form-label"
                >{{ field.label }}</label
              >

              <input
                id="{{ field.label }}"
                type="{{ field.field.widget.input_type }}"
                name="{{ field.name }}"
                class="form-control"
                value="{{ field.value|default:'' }}"
              />
              {% for error in field.errors %}
              <div class="form-text animate__animated animate__headShake">
                {{ error }}
              </div>
              {% endfor %}
            </div>
            {% endfor %}
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
              <a href="{% url 'countries:index' %}" class="btn btn-secondary">
                Back
              </a>
              <button type="submit" class="btn btn-primary">Create</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

countries/templates/countries/delete.html
{% extends "base.html" %} {% block title %} Delete Country | BRCG 🚀 {% endblock %} {% block content %}
<div class="d-flex align-items-center justify-content-center vh-100">
  <div class="row container-lg justify-content-center">
    <div class="col-12 col-sm-6">
      <div class="card shadow">
        <div class="card-header text-center fw-bold">Delete Country</div>

        <div class="card-body">
          <form action="{% url 'countries:delete' pk=object.pk %}" method="post">
            {% csrf_token %}
            <p class="text-center">
              Are you sure you want to delete "<b>{{ object }}</b>"?
            </p>
            <div class="d-grid gap-2 d-md-flex justify-content-md-center">
              <a href="{% url 'countries:index' %}" class="btn btn-secondary">
                Back
              </a>
              <button type="submit" class="btn btn-danger">Delete</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

countries/templates/countries/edit.html
{% extends "base.html" %} {% block title %} Edit Country | BRCG 🚀 {% endblock %}
{% block content %}
<div class="d-flex align-items-center justify-content-center vh-100">
  <div class="row container-lg justify-content-center">
    <div class="col-12 col-sm-10">
      <div class="card shadow">
        <div class="card-header text-center fw-bold">Edit Country</div>

        <div class="card-body">
          <form action="{% url 'countries:edit' pk=object.pk %}" method="post">
            {% csrf_token %} {% for field in form %}
            <div class="mb-3">
              <label for="{{ field.label }}" class="form-label"
                >{{ field.label }}</label
              >

              <input
                id="{{ field.label }}"
                type="{{ field.field.widget.input_type }}"
                name="{{ field.name }}"
                class="form-control"
                value="{{ field.value|default:'' }}"
              />
              {% for error in field.errors %}
              <div class="form-text animate__animated animate__headShake">
                {{ error }}
              </div>
              {% endfor %}
            </div>
            {% endfor %}
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
              <a href="{% url 'countries:index' %}" class="btn btn-secondary">
                Back
              </a>
              <button type="submit" class="btn btn-primary">Save</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

countries/templates/countries/index.html
{% extends "accounts/base.html" %} {% block title %} Countries Management | BRCG
🚀 {%endblock %} {% block content %}
<div class="container-fluid min-vh-100 pt-3 pb-2">
  <h3 class="text-center">Country Management</h3>
  <div class="d-flex justify-content-end">
    <a href="{% url 'countries:create' %}">
      <button type="button" class="btn btn-primary btn-sm">Add Country</button>
    </a>
  </div>

  <hr />

  <div class="container-fluid border rounded">
    <div class="table-responsive">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Flag</th>
            <th scope="col">Currency</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for country in object_list %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ country.name }}</td>
            <td>{{ country.flag }}</td>
            <td>{{ country.currency }}</td>
            <td>
              <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <a href="{% url 'countries:edit' pk=country.pk %}">
                  <button type="button" class="btn btn-warning btn-sm">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="16"
                      height="16"
                      fill="currentColor"
                      class="bi bi-pencil"
                      viewBox="0 0 16 16"
                    >
                      <path
                        d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"
                      />
                    </svg>
                  </button>
                </a>
                <a href="{% url 'countries:delete' pk=country.pk %}">
                  <button type="button" class="btn btn-danger btn-sm">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="16"
                      height="16"
                      fill="currentColor"
                      class="bi bi-trash"
                      viewBox="0 0 16 16"
                    >
                      <path
                        d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"
                      />
                      <path
                        d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"
                      />
                    </svg></button
                ></a>
              </div>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

  <!-- pagination -->
  <div class="div mt-2 d-flex justify-content-center">
    <ul class="pagination">
      {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
          >Previous</a
        >
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#">Previous</a>
      </li>
      {% endif %}
      <li class="page-item">
        <span class="current page-link disabled">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>
      </li>
      {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}"
          >Next</a
        >
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#">Next</a>
      </li>
      {% endif %}
    </ul>
  </div>
  <!-- end:pagination -->
</div>
{% endblock %}