app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/accounts/", include("accounts.api.urls", namespace="accounts-api")),
    path("api/categories/", include("categories.api.urls", namespace="categories-api")),
    path("api/calculate/", include("calculate.api.urls", namespace="calculate-api")),
    path("api/countries/", include("countries.api.urls", namespace="countries-api")),
    path(
        "api/destination/", include("destination.api.urls", namespace="destination-api")
    ),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("countries/", include("countries.urls", namespace="countries")),
    path("categories/", include("categories.urls", namespace="categories")),
]

categories/api/urls.py
from django.urls import path

from .views import CategoryListAPIView

urlpatterns = [
    path("", CategoryListAPIView.as_view(), name="index"),
]

app_name = "categories"

categories/urls.py
from django.urls import path

from .views import (
    CategoryListView,
    CreateCategoryView,
    DeleteCategoryView,
    UpdateCategoryView,
)

urlpatterns = [
    path("", CategoryListView.as_view(), name="index"),
    path("create/", CreateCategoryView.as_view(), name="create"),
    path("<int:pk>/delete/", DeleteCategoryView.as_view(), name="delete"),
    path("<int:pk>/update/", UpdateCategoryView.as_view(), name="update"),
]

app_name = "categories"

categories/models.py
from django.db import models

from countries.models import Country


class Category(models.Model):
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=255)
    price_per_kilo = models.FloatField()

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self) -> str:
        return self.title

categories/forms.py
from django.forms import ModelForm, Select

from .models import Category


class CreateCategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = [
            "country",
            "title",
            "price_per_kilo",
        ]
        widgets = {
            "country": Select(attrs={"class": "form-select"}),
        }


class UpdateCategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = [
            "country",
            "title",
            "price_per_kilo",
        ]
        widgets = {
            "country": Select(attrs={"class": "form-select"}),
        }

categories/api/views.py
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import filters
from rest_framework.generics import ListAPIView

from categories.models import Category
from categories.serializers import CategorySerializer


class CategoryListAPIView(ListAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer
    filter_backends = [DjangoFilterBackend, filters.SearchFilter]
    filterset_fields = ["country_id"]
    search_fields = ["title"]

categories/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from .forms import CreateCategoryForm, UpdateCategoryForm
from .models import Category


class CategoryListView(ListView):
    model = Category
    queryset = Category.objects.all().order_by("-id")
    paginate_by = 10
    template_name = "categories/index.html"


class UpdateCategoryView(UpdateView):
    model = Category
    form_class = UpdateCategoryForm
    template_name = "categories/update.html"
    success_url = reverse_lazy("categories:index")


class CreateCategoryView(CreateView):
    model = Category
    form_class = CreateCategoryForm
    template_name = "categories/create.html"
    success_url = reverse_lazy("categories:index")


class DeleteCategoryView(DeleteView):
    model = Category
    template_name = "categories/delete.html"
    success_url = reverse_lazy("categories:index")

categories/templates/categories/create.html
{% extends 'base.html' %} {% block title %}
  Create Category | BRCG 🚀
{% endblock %}
{% block content %}
  <div class="d-flex align-items-center justify-content-center vh-100">
    <div class="row container-md justify-content-center">
      <div class="col-12 col-sm-10">
        <div class="card shadow">
          <div class="card-header text-center fw-bold">Create Category</div>

          <div class="card-body">
            <form action="{% url 'categories:create' %}" method="post">
              {% csrf_token %}
              {% for field in form %}
                {% if field.field.widget.input_type == 'select' and field.name == 'country' %}
                  <div class="mb-3">
                    <label for="{{ form.country.id_for_label }}" class="form-label">{{ form.country.label }}</label>
                    {{ form.country }} {% for error in form.country.errors %}
                      <div class="form-text animate__animated animate__headShake">{{ error }}</div>
                    {% endfor %}
                  </div>
                {% else %}
                  <div class="mb-3">
                    <label for="{{ field.label }}" class="form-label">{{ field.label }}</label>

                    <input id="{{ field.label }}" type="{{ field.field.widget.input_type }}" name="{{ field.name }}" class="form-control" value="{{ field.value|default:'' }}" />
                    {% for error in field.errors %}
                      <div class="form-text animate__animated animate__headShake">{{ error }}</div>
                    {% endfor %}
                  </div>
                {% endif %}
              {% endfor %}
              <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <a href="{% url 'categories:index' %}" class="btn btn-secondary">Back</a>
                <button type="submit" class="btn btn-primary">Create</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

categories/templates/categories/delete.html
{% extends 'base.html' %} {% block title %}
  Delete Category | BRCG 🚀
{% endblock %} {% block content %}
  <div class="d-flex align-items-center justify-content-center vh-100">
    <div class="row container-lg justify-content-center">
      <div class="col-12 col-sm-7">
        <div class="card shadow">
          <div class="card-header text-center fw-bold">Delete Category</div>

          <div class="card-body">
            <form action="{% url 'categories:delete' pk=object.id %}" method="post">
              {% csrf_token %}
              <p class="text-center">
                Are you sure you want to delete "<b>{{ object }}</b>"?
              </p>
              <div class="d-grid gap-2 d-md-flex justify-content-md-center">
                <a href="{% url 'categories:index' %}" class="btn btn-secondary">Back</a>
                <button type="submit" class="btn btn-danger">Delete</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

categories/templates/categories/index.html
{% extends "accounts/base.html" %}
{% block title %}
  Categories Management | BRCG 🚀
{% endblock title %}
{% block content %}
  <div class="container-fluid min-vh-100 pt-3 pb-2">
    <h3 class="text-center">Category Management</h3>
    <div class="d-flex justify-content-end">
      <a href="{% url 'categories:create' %}">
        <button type="button" class="btn btn-primary btn-sm">Add Category</button>
      </a>
    </div>
    <hr />
    <div class="container-fluid border rounded">
      <div class="table-responsive">
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Country</th>
              <th scope="col">Country ID</th>
              <th scope="col">Title</th>
              <th scope="col">Price Per Kilo</th>
              <th scope="col">Actions</th>
            </tr>
          </thead>
          <tbody>
            {% for category in object_list %}
              <tr>
                <th scope="row">{{ page_obj.start_index|add:forloop.counter0 }}</th>
                <td>{{ category.country }}</td>
                <td>{{ category.country.id }}</td>
                <td>{{ category.title }}</td>
                <td>{{ category.price_per_kilo }}</td>
                <td>
                  <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    <a href="{% url 'categories:update' pk=category.pk %}">
                      <button type="button" class="btn btn-warning btn-sm">
                        <svg xmlns="http://www.w3.org/2000/svg"
                             width="16"
                             height="16"
                             fill="currentColor"
                             class="bi bi-pencil"
                             viewBox="0 0 16 16">
                          <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z" />
                        </svg>
                      </button>
                    </a>
                    <a href="{% url 'categories:delete' pk=category.id %}">
                      <button type="button" class="btn btn-danger btn-sm">
                        <svg xmlns="http://www.w3.org/2000/svg"
                             width="16"
                             height="16"
                             fill="currentColor"
                             class="bi bi-trash"
                             viewBox="0 0 16 16">
                          <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z" />
                          <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z" />
                        </svg>
                      </button>
                    </a>
                  </div>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <!-- pagination -->
    <div class="div mt-2 d-flex justify-content-center">
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#">Previous</a>
          </li>
        {% endif %}
        <li class="page-item">
          <span class="current page-link disabled">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
        </li>
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#">Next</a>
          </li>
        {% endif %}
      </ul>
    </div>
    <!-- end:pagination -->
  </div>
{% endblock content %}

categories/templates/categories/update.html
{% extends "base.html" %}
{% block title %}
  Update Category | BRCG 🚀
{% endblock title %}
{% block content %}
  <div class="d-flex align-items-center justify-content-center vh-100">
    <div class="row container-md justify-content-center">
      <div class="col-12 col-sm-10">
        <div class="card shadow">
          <div class="card-header text-center fw-bold">Update Category</div>
          <div class="card-body">
            <form action="{% url 'categories:update' pk=object.pk %}" method="post">
              {% csrf_token %}
              {% for field in form %}
                {% if field.field.widget.input_type == 'select' and field.name == 'country' %}
                  <div class="mb-3">
                    <label for="{{ form.country.id_for_label }}" class="form-label">{{ form.country.label }}</label>
                    {{ form.country }}
                    {% for error in form.country.errors %}
                      <div class="form-text animate__animated animate__headShake">{{ error }}</div>
                    {% endfor %}
                  </div>
                {% else %}
                  <div class="mb-3">
                    <label for="{{ field.label }}" class="form-label">{{ field.label }}</label>
                    <input id="{{ field.label }}"
                           type="{{ field.field.widget.input_type }}"
                           name="{{ field.name }}"
                           class="form-control"
                           value="{{ field.value|default:'' }}" />
                    {% for error in field.errors %}
                      <div class="form-text animate__animated animate__headShake">{{ error }}</div>
                    {% endfor %}
                  </div>
                {% endif %}
              {% endfor %}
              <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <a href="{% url 'categories:index' %}" class="btn btn-secondary">Back</a>
                <button type="submit" class="btn btn-primary">Save</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}